services:
  web:
    build: .
    entrypoint: /bin/entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data
    env_file:
      .env
    ports:
      - 5432:5432

volumes:
  postgresdb: